# shellcheck shell=bash
# shellcheck disable=SC2154 # tag, fw_commit, repo, fw_names and the fw_source variables belong to the sourcing script
# The checks and the rewrite behind tools/open-update-pr.sh, kept in functions
# of their own so tools/test-open-update-pr.sh can run them on crafted input
# without a network, a token or a checkout. Sourced, never run. A function
# here reads only its arguments and the variables named above it; nothing here
# runs the app's content (a Cargo.toml and a Cargo.lock are text to awk and perl).
#
# Trust, in one place (the long form is in open-update-pr.sh's header):
#   lock job     no token; clones an app (untrusted), runs `cargo update` in it;
#                its whole output is the directory `base`, `locks`, `files/`.
#                Everything in it may be forged.
#   publish job  the token; reads that directory as data and the app only as
#                git objects; pushes what these functions accept.

# Moves the pins in the Cargo.toml files named, in place. Only inline tables
# naming this repository; the pin key may come before or after `git`. A rev
# pin moves to $fw_commit, any other to the tag ($tag, $fw_commit are set by
# the caller and checked there: v<number>.<number>.<number>, 40 hex digits).
move_pins() {
    # shellcheck disable=SC2016 # perl, not shell, expands these
    TAG=$tag COMMIT=$fw_commit timeout 60 perl -0pi -e '
        sub pin { $_[0] eq "rev" ? qq(rev = "$ENV{COMMIT}") : qq(tag = "$ENV{TAG}") }
        s#(telamon-framework-[a-z0-9-]+\s*=\s*\{[^}\n]*?github\.com/EternalCoder454/atlas-framework(?:\.git)?"[^}\n]*?)\b(rev|tag|branch)\s*=\s*"[^"]*"#$1 . pin($2)#ge;
        s#(telamon-framework-[a-z0-9-]+\s*=\s*\{[^}\n]*?)\b(rev|tag|branch)\s*=\s*"[^"]*"([^}\n]*?github\.com/EternalCoder454/atlas-framework(?:\.git)?")#$1 . pin($2) . $3#ge;
    ' -- "$@"
}

# Lists tree-ish $1 of the repository in the current directory into $2. A
# failure (a bad ref, a damaged repository) stops the script here: inside
# blobs_named's process substitution it would read as "no manifests".
list_tree() {
    if ! git ls-tree -r -z "$1" >"$2"; then
        echo "::error::git ls-tree failed for $1; not going on with an empty file list" >&2
        exit 1
    fi
}

# Paths of regular-file blobs (mode 100644) named $1 in the listing in file
# $2 (from list_tree), one per line. Symlinks (120000) and anything under one
# are not blobs of this kind, so they never appear; neither does a path with a
# control character (it could not be told apart from two lines, or a workflow
# command).
blobs_named() {
    local entry meta path
    while IFS= read -r -d '' entry; do
        meta=${entry%%$'\t'*}
        path=${entry#*$'\t'}
        [ "${meta%% *}" = 100644 ] || continue
        [[ $path == *[[:cntrl:]]* ]] && continue
        case $path in "$1" | */"$1") printf '%s\n' "$path" ;; esac
    done <"$2"
}

# Whether the lock file $1 is written exactly as cargo writes one: the
# header, `version = N`, then [[package]] tables of name, version, source,
# checksum and a dependencies list, one key per line, each at most once, and at
# least one package (an empty file would pass for "no change"). Any
# other TOML (other spacing, indentation, other tables, inline arrays) could
# hide a package from lock_packages, so it is refused. So is any byte but
# printable ASCII and the line feed (a tab or a CR splits a field in awk and
# means nothing in TOML; a NUL ends a line in some awks), and any value with a
# character outside the ones cargo writes into names, versions, sources and
# checksums: awk, TOML and the URL parser of cargo must all read the same string
# (the URL parser drops tabs and newlines, so "index<TAB>/../../x" is one
# address to cargo and another to awk).
lock_shaped() {
    if LC_ALL=C grep -aq '[^[:print:]]' -- "$1"; then
        return 1
    fi
    LC_ALL=C awk '
        NR == 1 { if ($0 != "# This file is automatically @generated by Cargo.") exit 1; next }
        inarr && $0 ~ "^ \"[-A-Za-z0-9._+~/:#?=@%&,;!* ()]+\",$" { next }
        inarr && /^\]$/ { inarr = 0; next }
        inarr { exit 1 }
        /^$/ || /^# / { next }
        !pkg && /^version = [0-9]+$/ && !top++ { next }
        /^\[\[package\]\]$/ { pkg = 1; split("", seen); next }
        pkg && $0 ~ "^(name|version|source|checksum) = \"[-A-Za-z0-9._+~/:#?=@%&,;!*]+\"$" && !seen[$1]++ { next }
        pkg && /^dependencies = \[$/ && !seen["dependencies"]++ { inarr = 1; next }
        { exit 1 }
        END { if (inarr || !pkg) exit 1 }' "$1"
}

# "name version source" of every package in the lock file $1, sorted. Only
# for files lock_shaped accepts.
lock_packages() {
    awk '/^\[\[package\]\]/ { if (n != "") print n, v, src; n = v = src = ""; next }
         /^name = /    { n = $3 } /^version = / { v = $3 } /^source = / { src = $3 }
         END { if (n != "") print n, v, src }' "$1" | tr -d '"' | LC_ALL=C sort
}

# "name version source checksum" ("-" for none), unsorted: for lock_checksum_drift.
lock_packages_checksums() {
    awk '/^\[\[package\]\]/ { if (n != "") print n, v, (src == "" ? "-" : src), (sum == "" ? "-" : sum); n = v = src = sum = ""; next }
         /^name = /    { n = $3 } /^version = / { v = $3 } /^source = / { src = $3 } /^checksum = / { sum = $3 }
         END { if (n != "") print n, v, (src == "" ? "-" : src), (sum == "" ? "-" : sum) }' "$1" | tr -d '"'
}

# Packages ("name version") that are in both lock files $1 (old) and $2 (new)
# from the same source with a different checksum. `cargo update` never does
# that: a version of a crate is one file. Only for files lock_shaped accepts.
lock_checksum_drift() {
    awk 'NR == FNR { sum[$1 " " $2 " " $3] = $4; next }
         ($1 " " $2 " " $3) in sum && sum[$1 " " $2 " " $3] != $4 { print $1, $2 }' \
        <(lock_packages_checksums "$1") <(lock_packages_checksums "$2")
}

# Sets the sources a telamon-framework crate may have in a lock file after an
# update to $tag at $fw_commit (git in a lock file is written with or without
# `.git`, with the tag or with the rev), and the one registry other crates may
# come from.
set_fw_sources() {
    fw_source="git+https://github.com/EternalCoder454/atlas-framework?tag=$tag#$fw_commit"
    fw_source_git="git+https://github.com/EternalCoder454/atlas-framework.git?tag=$tag#$fw_commit"
    fw_source_rev="git+https://github.com/EternalCoder454/atlas-framework?rev=$fw_commit#$fw_commit"
    fw_source_rev_git="git+https://github.com/EternalCoder454/atlas-framework.git?rev=$fw_commit#$fw_commit"
    crates_io="registry+https://github.com/rust-lang/crates.io-index"
}

# Whether the lock file $2, from the lock job, is a change a framework update
# can make to the lock file $1 of the base: every package that is new or
# changed is a telamon-framework crate at exactly the framework commit, or a
# crates.io package the base or the framework's own lock already had; no
# package already there changed its checksum. Prints the reasons; appends a
# line to the array `others` for each crates.io package the update touched.
# $3 is the lock's path, for messages; $fw_names (the framework lock's package
# names, one per line), $repo and set_fw_sources' variables are set.
lock_change_ok() {
    local old=$1 new=$2 lock=$3 base_names name version source shown bad=0
    base_names=$(lock_packages "$old" | cut -d' ' -f1 | LC_ALL=C sort -u)
    while read -r name version source; do
        shown="${lock//[^A-Za-z0-9 ._\/-]/?}: ${name//[^A-Za-z0-9._-]/?} ${version//[^A-Za-z0-9.+-]/?}"
        if [[ $name == telamon-framework-* ]]; then
            if [ "$source" = "$fw_source" ] || [ "$source" = "$fw_source_git" ] ||
                [ "$source" = "$fw_source_rev" ] || [ "$source" = "$fw_source_rev_git" ]; then
                continue
            fi
        elif [ "$source" = "$crates_io" ] &&
            grep -qxF -- "$name" <<<"$base_names"$'\n'"$fw_names"; then
            # For the reviewer: anything else the update changed.
            others+=("$shown")
            continue
        fi
        echo "::error::$repo: the lock job's $shown is not from crates.io or telamon-framework $tag (${source//[^A-Za-z0-9._:\/+#?=-]/?})"
        bad=1
    done < <(LC_ALL=C comm -13 <(lock_packages "$old") <(lock_packages "$new"))
    while read -r name version; do
        echo "::error::$repo: the lock job changed the checksum of ${lock//[^A-Za-z0-9 ._\/-]/?}: ${name//[^A-Za-z0-9._-]/?} ${version//[^A-Za-z0-9.+-]/?}"
        bad=1
    done < <(lock_checksum_drift "$old" "$new")
    [ "$bad" = 0 ]
}

# Whether directory $1 holds exactly what the lock job writes: `base`, `locks`
# and `files/`, nothing else, none of them a link.
lock_output_shaped() {
    local dir=$1
    [ "$(find "$dir" -mindepth 1 -maxdepth 1 -printf '%f\n' 2>/dev/null | LC_ALL=C sort | tr '\n' ' ')" = "base files locks " ] &&
        [ ! -L "$dir/base" ] && [ -f "$dir/base" ] && [ ! -L "$dir/locks" ] && [ -f "$dir/locks" ] &&
        [ ! -L "$dir/files" ] && [ -d "$dir/files" ]
}

# Whether directory $1 says "no lock file changed": `locks` empty, `base` a
# plain file, and nothing else but the (empty, possibly dropped) files/.
lock_output_empty() {
    local dir=$1
    [ -f "$dir/locks" ] && [ ! -L "$dir/locks" ] && [ ! -s "$dir/locks" ] &&
        [ -f "$dir/base" ] && [ ! -L "$dir/base" ] &&
        [ "$(find "$dir" -mindepth 1 -maxdepth 1 ! -name base ! -name locks ! -name files -printf x | wc -c)" = 0 ]
}

# Prints the path of lock file $2 (a path the lock job listed, relative) inside
# the lock job's output $1, and succeeds only when it is a plain file below
# $1/files, not through a link or a `..`, of at most 8 MiB, written as cargo
# writes a lock file.
lock_output_file() {
    local dir=$1 lock=$2 file real
    file=$dir/files/$lock
    real=$(realpath -e -- "$file" 2>/dev/null || true)
    [ "$real" = "$(realpath -- "$dir/files")/$lock" ] && [ -f "$file" ] &&
        [ "$(stat -c %s "$file")" -le 8388608 ] && lock_shaped "$file" &&
        printf '%s\n' "$file"
}
