[package]
name = "atlas-framework-flatpak"
description = "Flatpak through libflatpak, for Atlas Updater and Atlas Store (needs flatpak-devel to build)"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
libflatpak = "0.7"
